### PR TITLE
Add instructions for automating Google Play Store version number bumps

### PR DESCRIPTION
**Pull request by adamgall**
Include instructions on how to automatically pull the number of git commits, and use that as the incrementing `versionCode` in binaries. Additionally, grab the `version` value from `package.json` and use that as the user-displayed version number.

### CODE REVIEW

**Comment by AurelGit** [comment]
Hey @adamgall !

Thanks so much for this PR, really interesting.

I'll test it really soon.

Do you think it's a good practice to use the number of commits as versionCode ? What about your experience with this kind of usage ?

**Comment by adamgall** [comment]
Well, it's certainly not a bulletproof methodology.

It works well given the following conditions:

- you have a "trunk" branch which is used for creating builds. Like `develop` or `master`.
- you do new work in branches off of your main trunk.
- after you merge your work into your trunk, you do a release.

If this method is followed, then I don't think there will ever be a problem.

Issues will pop up if you reset your trunk branch back by 1 or more commits, and attempt to re-distribute.

My experience with this method is very minimal, I just recently got it set up in my project, but it's been working well for the last few weeks. I've got a CI/CD pipeline set up, so my build server automatically does builds and distributions whenever code is merged into `develop` (`develop` is my "trunk"). Given that I'm doing development using the steps I outlined above, I haven't had any issues with this yet.

**Comment by adamgall** [comment]
Maybe it makes sense to add these "conditions" into the docs, as well, so that people know what they're getting into?

**Comment by AurelGit** [comment]
And what about a versionCode based on the current timestamp ?

**Comment by adamgall** [comment]
Oooo I like that idea a lot! That seems a lot safer than using fit commit counts, tbh.

The only downside is that the number will be “really big”.

Maybe, upon initial set up in any specific project, you take the current timestamp, embed that static number as a variable, and subtract it from the “current” timestamp which is calculated each build. Then you end up with build numbers that start close to zero, relatively speaking.

**Pull request closed without merging**
