### PR TITLE
Feature/add i18n

### PR DESCRIPTION
**Pull request by alejandropaciotti**
This PR implement the [react-native-languages](https://github.com/react-community/react-native-languages) library.

Following this [example](https://github.com/react-community/react-native-languages/tree/master/example/src).

Files changed:

- App/Containers/Example/ExampleScreen.js

Files added:

- App/App.js
- App/Locales/traslations/en.json
- App/Locales/traslations/es.json
- App/Locales/i18n.js

### CODE REVIEW

**Comment by AurelGit** [comment]
Thanks @alejandropaciotti ! Really useful feature.

It seems that `react-native-i18n` is now deprecated, do you think it's possible to use [`react-native-languages`](https://github.com/react-community/react-native-languages) ?
Did you choose `react-native-i18n` for a particular reason ?

In any case, love your contribution :)

**Comment by AurelGit** [comment]
> It seems that `react-native-i18n` is now deprecated, do you think it's possible to use [`react-native-languages`](https://github.com/react-community/react-native-languages) ?

Or maybe a more maintened one like [`vue-i18n`](https://github.com/kazupon/vue-i18n) ?
Choice most probably be important to be safe in future.

**Comment by alejandropaciotti** [comment]
> Thanks @alejandropaciotti ! Really useful feature.
> 
> It seems that `react-native-i18n` is now deprecated, do you think it's possible to use [`react-native-languages`](https://github.com/react-community/react-native-languages) ?
> Did you choose `react-native-i18n` for a particular reason ?
> 
> In any case, love your contribution :)

I found that react-native-i18n is deprecated once I finalized the PR.
I'll change for the react-native-languages library.

**Comment by JeremyDolle** [comment]
Hi @alejandropaciotti , it doesn't seem to work on android probably because of gradle's version. Did you have an error like this on android ?

```
* What went wrong:
A problem occurred evaluating project ':react-native-languages'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by alejandropaciotti** [comment]
> Hi @alejandropaciotti , it doesn't seem to work on android probably because of gradle's version. Did you have an error like this on android ?
> 
> ```
> * What went wrong:
> A problem occurred evaluating project ':react-native-languages'.
> > Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> ```

Sorry Jeremy, I haven't tried in Android yet. But I will

**Comment by AurelGit** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue or need to implement this feature.

Thank you!

**Pull request closed without merging**
